name: Call Release Please

on:
  push:
    branches:
      - master

jobs:
  bigquery-sink-tests:
    uses: entur/gh-workflows/.github/workflows/release-please.yml@main
    with:
      release_type: terraform-module
      version_bumped_files: |
        README.md
        examples/init/main.tf
